version: 2.1

orbs:
  shellcheck: circleci/shellcheck@1.3.4

executors:
  default:
    working_directory: /go/src/github.com/mattermost/mattermost-operator
    docker:
      - image: circleci/golang:1.14.4

jobs:
  lint:
    executor:
      name: default
    steps:
      - checkout
      - run: make check-style

  generate:
    executor:
      name: default
    steps:
      - checkout
      - run: |
          make clean
          make operator-sdk
      - run: |
          mkdir -p /tmp/pkg/apis/mattermost/v1alpha1
          cp -R pkg/apis/mattermost/v1alpha1/* /tmp/pkg/apis/mattermost/v1alpha1
      - run: |
          mkdir -p /tmp/deploy/crds
          cp -R deploy/crds/* /tmp/deploy/crds
      - run: make generate
      - run: diff /tmp/pkg/apis/mattermost/v1alpha1 pkg/apis/mattermost/v1alpha1
      - run: diff /tmp/deploy/crds deploy/crds

  unittest:
    executor:
      name: default
    steps:
      - checkout
      - run: |
          make unittest
          make goverall

  e2e:
    environment:
      - K8S_VERSION=v1.17.5
      - IMAGE_NAME=mattermost/mattermost-operator
      - IMAGE_TAG=test
      - KIND_VERSION=v0.8.1
      - SDK_VERSION=v0.18.2
    machine: true
    resource_class: 2xlarge
    working_directory: /home/circleci/.go_workspace/src/github.com/mattermost/mattermost-operator
    steps:
      - checkout
      - run:
          name: Kind
          command: ./test/e2e.sh
          no_output_timeout: 1h

  push-docker-pr:
    executor:
      name: default
    steps:
      - checkout
      - setup_remote_docker
      - run: make build-image
      - run: |
          set -e
          set -u
          export TAG="${CIRCLE_SHA1:0:7}"
          echo $DOCKER_PASSWORD | docker login --username $DOCKER_USERNAME --password-stdin
          docker tag mattermost/mattermost-operator:test mattermost/mattermost-operator:$TAG
          docker push mattermost/mattermost-operator:$TAG

  push-docker:
    executor:
      name: default
    steps:
      - checkout
      - setup_remote_docker
      - run: make build-image
      - run: |
          set -e
          set -u
          if [[ -z "${CIRCLE_TAG:-}" ]]; then
            echo "Pushing lastest for $CIRCLE_BRANCH..."
            TAG=latest
          else
            echo "Pushing release $CIRCLE_TAG..."
            TAG="$CIRCLE_TAG"
          fi
          echo $DOCKER_PASSWORD | docker login --username $DOCKER_USERNAME --password-stdin
          docker tag mattermost/mattermost-operator:test mattermost/mattermost-operator:$TAG
          docker push mattermost/mattermost-operator:$TAG

workflows:
  version: 2
  untagged-build:
    jobs:
      - shellcheck/check:
          exclude: ./vendor/*
          filters:
            branches:
              ignore:
                - master
                - /^v.*/
      - lint:
          filters:
            branches:
              ignore:
                - master
                - /^v.*/
      - generate:
          filters:
            branches:
              ignore:
                - master
                - /^v.*/
      - unittest:
          requires:
            - lint
            - generate
          filters:
            branches:
              ignore:
                - master
                - /^v.*/
      - e2e:
          requires:
            - lint
            - unittest
          filters:
            branches:
              ignore:
                - master
                - /^v.*/

      - push-docker-pr:
          context: matterbuild-docker
          requires:
            - unittest
          filters:
            branches:
              ignore:
                - master
                - /^v.*/

  master-build:
    jobs:
      - lint:
          filters:
            branches:
              only:
                - master
      - unittest:
          filters:
            branches:
              only:
                - master
      - e2e:
          requires:
            - lint
            - unittest
          filters:
            branches:
              only:
                - master
      - push-docker:
          context: matterbuild-docker
          requires:
            - e2e
          filters:
            branches:
              only:
                - master
  tag-builds:
    jobs:
      - lint:
          filters:
            tags:
              only: /^v.*/
            branches:
              ignore: /.*/
      - unittest:
          filters:
            tags:
              only: /^v.*/
            branches:
              ignore: /.*/
      - e2e:
          requires:
            - lint
            - unittest
          filters:
            tags:
              only: /^v.*/
            branches:
              ignore: /.*/
      - push-docker:
          context: matterbuild-docker
          requires:
            - e2e
          filters:
            tags:
              only: /^v.*/
            branches:
              ignore: /.*/
