apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: clusterinstallations.mattermost.com
spec:
  group: mattermost.com
  names:
    kind: ClusterInstallation
    listKind: ClusterInstallationList
    plural: clusterinstallations
    singular: clusterinstallation
  scope: Namespaced
  subresources:
    status: {}
  validation:
    openAPIV3Schema:
      properties:
        apiVersion:
          description: 'APIVersion defines the versioned schema of this representation
            of an object. Servers should convert recognized schemas to the latest
            internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/api-conventions.md#resources'
          type: string
        kind:
          description: 'Kind is a string value representing the REST resource this
            object represents. Servers may infer this from the endpoint the client
            submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/api-conventions.md#types-kinds'
          type: string
        metadata:
          description: 'Standard objectâ€™s metadata. More info: https://github.com/kubernetes/community/blob/master/contributors/devel/api-conventions.md#metadata
            +k8s:openapi-gen=false'
          type: object
        spec:
          description: 'Specification of the desired behavior of the Mattermost cluster.
            More info: https://github.com/kubernetes/community/blob/master/contributors/devel/api-conventions.md#spec-and-status'
          properties:
            affinity:
              description: If specified, affinity will define the pod's scheduling
                constraints
              type: object
            databaseType:
              properties:
                externalDatabaseSecret:
                  description: If the user want to use an external DB. This can be
                    inside the same k8s cluster or outside like AWS RDS.
                  type: string
                type:
                  type: string
              type: object
            image:
              description: Image defines the ClusterInstallation Docker image.
              type: string
            ingressName:
              description: IngressName defines the name to be used when creating the
                ingress rules
              type: string
            minioStorageSize:
              description: MinioStorageSize defines the storage size for minio. ie
                50Gi
              type: string
            nodeSelector:
              additionalProperties:
                type: string
              description: 'NodeSelector is a selector which must be true for the
                pod to fit on a node. Selector which must match a node''s labels for
                the pod to be scheduled on that node. More info: https://kubernetes.io/docs/concepts/configuration/assign-pod-node/'
              type: object
            replicas:
              description: Replicas defines the number of Mattermost instances in
                a ClusterInstallation resource
              format: int32
              type: integer
            version:
              description: Version defines the ClusterInstallation Docker image version.
              type: string
          required:
          - ingressName
          type: object
        status:
          description: 'Most recent observed status of the Mattermost cluster. Read-only.
            Not included when requesting from the apiserver, only from the Mattermost
            Operator API itself. More info: https://github.com/kubernetes/community/blob/master/contributors/devel/api-conventions.md#spec-and-status'
          properties:
            replicas:
              description: Total number of non-terminated pods targeted by this Mattermost
                deployment (their labels match the selector).
              format: int32
              type: integer
            state:
              description: Represents the running state of the Mattermost instance
              type: string
            version:
              description: The version currently running in the Mattermost instance
              type: string
          type: object
      required:
      - spec
  version: v1alpha1
  versions:
  - name: v1alpha1
    served: true
    storage: true
